name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      uses: heroku/deploy-via-github-action@v2
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: moclaw-profile
